In [14]:
import pandas as pd
import numpy as np
import matplotlib as plt

plt.rcParams["figure.figsize"] = (8, 5)
plt.rcParams["font.size"] = 12

**Load CSV**

In [15]:
CSV_PATH = "../results/metrics.csv"

df = pd.read_csv(CSV_PATH)

print(f"Total Experiments : {len(df)}")

df.head()

Total Experiments : 96

,Image,Resolution,Payload,Payload_Size(Bytes),AES_Encrypt_Time(s),Dynamic_XOR_Time(s),Embedding_Time(s),Sender_Total_Time(s),Extraction_Time(s),XOR_Recovery_Time(s),AES_Decrypt_Time(s),Receiver_Total_Time(s),PSNR,MSE,NPCR,Entropy
0,aircraft_1024.png,1024x1024,100B.txt,100,0.000755,0.000221,0.002491,0.003467,0.000162,0.000149,0.000065,0.000375,86.405557,0.000149,0.014877,6.676904
1,aircraft_1024.png,1024x1024,1KB.txt,1024,0.000114,0.002016,0.002596,0.004726,0.001405,0.001277,0.000069,0.002751,77.033465,0.001287,0.128746,6.676903
2,aircraft_1024.png,1024x1024,250B.txt,250,0.000082,0.000411,0.000850,0.001343,0.000363,0.000326,0.000068,0.000757,83.043355,0.000323,0.032266,6.676904
3,aircraft_1024.png,1024x1024,2KB.txt,2048,0.000071,0.003422,0.004787,0.008280,0.002715,0.002548,0.000064,0.005327,73.954545,0.002616,0.261593,6.676914
4,aircraft_1024.png,1024x1024,4KB.txt,4096,0.000086,0.006848,0.009202,0.016136,0.005951,0.005411,0.000068,0.011430,70.972041,0.005198,0.519848,6.676924

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Image                   96 non-null     str
 1   Resolution              96 non-null     str
 2   Payload                 96 non-null     str
 3   Payload_Size(Bytes)     96 non-null     int64
 4   AES_Encrypt_Time(s)     96 non-null     float64
 5   Dynamic_XOR_Time(s)     96 non-null     float64
 6   Embedding_Time(s)       96 non-null     float64
 7   Sender_Total_Time(s)    96 non-null     float64
 8   Extraction_Time(s)      96 non-null     float64
 9   XOR_Recovery_Time(s)    96 non-null     float64
 10  AES_Decrypt_Time(s)     96 non-null     float64
 11  Receiver_Total_Time(s)  96 non-null     float64
 12  PSNR                    96 non-null     float64
 13  MSE                     96 non-null     float64
 14  NPCR                    96 non-null     float64
 15  Entropy                 96 non-null     float64
dtypes: float64(12), int64(1), str(3)
memory usage: 12.1 KB

In [17]:
df.isnull().sum()

Image                     0
Resolution                0
Payload                   0
Payload_Size(Bytes)       0
AES_Encrypt_Time(s)       0
Dynamic_XOR_Time(s)       0
Embedding_Time(s)         0
Sender_Total_Time(s)      0
Extraction_Time(s)        0
XOR_Recovery_Time(s)      0
AES_Decrypt_Time(s)       0
Receiver_Total_Time(s)    0
PSNR                      0
MSE                       0
NPCR                      0
Entropy                   0
dtype: int64

In [18]:
df.describe().round(4)

,Payload_Size(Bytes),AES_Encrypt_Time(s),Dynamic_XOR_Time(s),Embedding_Time(s),Sender_Total_Time(s),Extraction_Time(s),XOR_Recovery_Time(s),AES_Decrypt_Time(s),Receiver_Total_Time(s),PSNR,MSE,NPCR,Entropy
count,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000,96.0000
mean,1336.3333,0.0001,0.0023,0.0031,0.0055,0.0019,0.0018,0.0001,0.0038,69.5470,0.0365,3.6491,7.4002
std,1399.4210,0.0001,0.0025,0.0031,0.0056,0.0021,0.0019,0.0000,0.0040,8.6197,0.0734,7.3375,0.4335
min,100.0000,0.0000,0.0002,0.0002,0.0005,0.0002,0.0001,0.0000,0.0003,52.8687,0.0001,0.0140,6.6639
25%,250.0000,0.0000,0.0004,0.0006,0.0011,0.0004,0.0003,0.0000,0.0008,64.0757,0.0019,0.1909,7.2838
50%,762.0000,0.0001,0.0013,0.0022,0.0037,0.0012,0.0010,0.0001,0.0022,69.7943,0.0070,0.7019,7.5819
75%,2048.0000,0.0001,0.0034,0.0046,0.0081,0.0028,0.0026,0.0001,0.0054,75.3972,0.0265,2.6530,7.7171
max,4096.0000,0.0008,0.0086,0.0109,0.0189,0.0070,0.0064,0.0001,0.0125,86.6834,0.3359,33.5897,7.7625

**Number of Images**

In [19]:
print(df["Image"].unique())

<StringArray>
['aircraft_1024.png',  'aircraft_128.png',  'aircraft_256.png',
  'aircraft_512.png',   'baboon_1024.png',    'baboon_128.png',
    'baboon_256.png',    'baboon_512.png',    'house_1024.png',
     'house_128.png',     'house_256.png',     'house_512.png',
   'pepper_1024.png',    'pepper_128.png',    'pepper_256.png',
    'pepper_512.png']
Length: 16, dtype: str

**Resolutions**

In [20]:
print(sorted(df["Resolution"].unique()))

['1024x1024', '128x128', '256x256', '512x512']

**Payloads**

In [21]:
df[["Payload","Payload_Size(Bytes)"]].drop_duplicates().sort_values(
    "Payload_Size(Bytes)"
)

    Payload  Payload_Size(Bytes)
0  100B.txt                  100
2  250B.txt                  250
5  500B.txt                  500
1   1KB.txt                 1024
3   2KB.txt                 2048
4   4KB.txt                 4096

**Experiments per image**

In [22]:
df.groupby("Image").size()

Image
aircraft_1024.png    6
aircraft_128.png     6
aircraft_256.png     6
aircraft_512.png     6
baboon_1024.png      6
baboon_128.png       6
baboon_256.png       6
baboon_512.png       6
house_1024.png       6
house_128.png        6
house_256.png        6
house_512.png        6
pepper_1024.png      6
pepper_128.png       6
pepper_256.png       6
pepper_512.png       6
dtype: int64

**Average Metrics**

In [23]:
summary = df[
    [
        "PSNR",
        "MSE",
        "NPCR",
        "Entropy",
        "Sender_Total_Time(s)",
        "Receiver_Total_Time(s)"
    ]
].mean().round(4)

summary

PSNR                      69.5470
MSE                        0.0365
NPCR                       3.6491
Entropy                    7.4002
Sender_Total_Time(s)       0.0055
Receiver_Total_Time(s)     0.0038
dtype: float64

**Best PSNR**

In [24]:
df.loc[df["PSNR"].idxmax()]

Image                     baboon_1024.png
Resolution                      1024x1024
Payload                          100B.txt
Payload_Size(Bytes)                   100
AES_Encrypt_Time(s)               0.00007
Dynamic_XOR_Time(s)              0.000196
Embedding_Time(s)                0.000476
Sender_Total_Time(s)             0.000741
Extraction_Time(s)               0.000174
XOR_Recovery_Time(s)             0.000155
AES_Decrypt_Time(s)               0.00008
Receiver_Total_Time(s)           0.000409
PSNR                             86.68337
MSE                               0.00014
NPCR                             0.013955
Entropy                          7.753692
Name: 24, dtype: object

**Worst PSNR**

In [25]:
df.loc[df["PSNR"].idxmin()]

Image                     house_128.png
Resolution                      128x128
Payload                         4KB.txt
Payload_Size(Bytes)                4096
AES_Encrypt_Time(s)            0.000042
Dynamic_XOR_Time(s)            0.008609
Embedding_Time(s)              0.008725
Sender_Total_Time(s)           0.017376
Extraction_Time(s)             0.005986
XOR_Recovery_Time(s)           0.005684
AES_Decrypt_Time(s)            0.000114
Receiver_Total_Time(s)         0.011783
PSNR                          52.868745
MSE                            0.335897
NPCR                          33.589681
Entropy                        7.493058
Name: 58, dtype: object

In [26]:
summary_table = df.describe().round(4)

summary_table.to_csv("../results/summary_statistics.csv")